---
name: Net-Amazon-SimpleQueue
version: 0.30
author:
  - 'Leon Brocard C<acme@astray.com>'
abstract: DEPRECATED Use the Amazon Simple Queue Service
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  IO::Prompt: 0
  LWP::UserAgent: 0
  Module::Build: 0
  Test::Exception: 0.15
  Test::More: 0.01
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
configure_requires:
  Module::Build: 0.35
provides:
  Net::Amazon::SimpleQueue:
    file: lib/Net/Amazon/SimpleQueue.pm
    version: 0.30
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
